import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await page.getByRole('heading',{name:'Your time, everywhere.'}).waitFor();
await page.getByRole('button',{name:'Add city',exact:true}).click();
await page.getByPlaceholder('Search cities or time zones').fill('London');
await page.getByRole('button',{name:/LON London United Kingdom/}).click();
assert.equal(await page.locator('.city-card').count(),4);
await page.getByRole('button',{name:'Remove London',exact:true}).click();
await page.getByLabel('Date',{exact:true}).fill('2026-09-29');
await page.getByLabel('Time',{exact:true}).fill('00:30');
await page.getByLabel('Duration',{exact:true}).selectOption('60');
assert.match(await page.locator('.city-card').nth(1).innerText(),/8:30/);
assert.match(await page.locator('.city-card').nth(2).innerText(),/11:30/);
await page.getByRole('button',{name:'Save availability',exact:true}).click();
await page.getByRole('button',{name:/Your saved times/}).click();
assert.equal(await page.locator('.saved-time').count(),1);
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByLabel('Calendar time zone').selectOption('new-york');
assert.equal(await page.getByLabel('Time',{exact:true}).inputValue(),'11:30');
assert.equal(await page.getByLabel('Date',{exact:true}).inputValue(),'2026-09-28');
await page.getByRole('button',{name:'Connect calendar'}).click();
const ics='BEGIN:VCALENDAR\r\nVERSION:2.0\r\nX-WR-CALNAME:QA calendar\r\nBEGIN:VEVENT\r\nUID:qa\r\nDTSTART:20260929T140000Z\r\nDTEND:20260929T150000Z\r\nSUMMARY:Test interview\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:qa-two\r\nDTSTART:20260929T140000Z\r\nDTEND:20260929T150000Z\r\nSUMMARY:Second interview\r\nEND:VEVENT\r\nEND:VCALENDAR';
await page.locator('input[type=file]').setInputFiles({name:'qa.ics',mimeType:'text/calendar',buffer:Buffer.from(ics)});
await page.getByText('QA calendar',{exact:true}).waitFor();
await page.getByRole('button',{name:'Close dialog'}).click();
assert.equal(await page.locator('.imported-event').count(),2);
const boxes=await page.locator('.imported-event').evaluateAll(els=>els.map(el=>({left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right})));
assert.ok(Math.abs(boxes[0].left-boxes[1].left)<1&&Math.abs(boxes[0].right-boxes[1].right)<1,'overlapping events share the day column width');
await page.getByLabel('Date',{exact:true}).fill('2026-09-29');
await page.getByLabel('Time',{exact:true}).fill('10:00');
await page.getByText('Overlaps 2 calendar events.').waitFor();
await page.getByRole('button',{name:'Next week',exact:true}).click();
await page.getByText('Overlaps 2 calendar events.').waitFor();
await page.reload();
assert.equal(await page.locator('.imported-event').count(),2);
await page.getByRole('button',{name:/My calendars/}).click();
await page.getByRole('button',{name:'Remove QA calendar'}).click();
await page.getByRole('button',{name:'iCloud link'}).click();
await page.getByRole('textbox',{name:'Public iCloud calendar link'}).fill('https://example.com/calendar.ics');
await page.getByRole('button',{name:'Connect read-only calendar'}).click();
await page.getByRole('alert').filter({hasText:'Use an iCloud public calendar link or a Google Calendar iCal link.'}).waitFor();
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('button',{name:/Your saved times/}).click();
await page.getByRole('button',{name:/Delete saved time/}).click();
await page.getByRole('button',{name:'Find a time',exact:true}).click();
await page.getByLabel('Calendar time zone').selectOption('seoul');
await page.getByLabel('Date',{exact:true}).fill('2026-09-29');
await page.getByLabel('Time',{exact:true}).fill('22:00');
assert.equal(await page.locator('.time-cell[tabindex="0"]').count(),1);
await page.locator('.time-cell[tabindex="0"]').focus();
await page.keyboard.press('ArrowDown');
assert.equal(await page.getByLabel('Time',{exact:true}).inputValue(),'22:30');
await page.getByLabel('Time',{exact:true}).fill('22:00');
const visible=await page.locator('.city-comparisons').evaluate(el=>el.clientHeight>=el.scrollHeight-1);
assert.ok(visible,'all three city comparisons should be visible');
await page.getByRole('heading',{name:'Your time, everywhere.'}).click();
await page.mouse.move(0,0);
await page.waitForTimeout(200);
await fs.mkdir('.impeccable/review',{recursive:true});
await page.screenshot({path:'.impeccable/review/desktop.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'desktop horizontal overflow');
await page.setViewportSize({width:1366,height:900});
await page.screenshot({path:'.impeccable/review/desktop-1366.png',fullPage:true});
const actionBox=await page.getByRole('button',{name:'Save availability',exact:true}).boundingBox();
const panelBox=await page.locator('.time-panel').boundingBox();
assert.ok(actionBox.y+actionBox.height<=panelBox.y+panelBox.height,'save action should fit the desktop panel');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'.impeccable/review/mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile horizontal overflow');
assert.deepEqual(errors,[]);
console.log('Browser checks passed: city controls, timezone conversion, save/delete, calendar import and persistence, invalid feed rejection, desktop/mobile overflow.');
await browser.close();
